name: Cypress Tests

on: 
  pull_request:
    branches: [main]
defaults:
  run:
    working-directory: sep6
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    container: cypress/included:3.8.3
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build npm package
        run: npm init -y && npm install && npm run build
      - name: Cypress run tests
        run: cypress run
 
