name: Cypress Tests

on: [push]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Setup npm package
        run: npm init -y && npm install && npm install -g @vue/cli@latest
      - name: Build proj
        working-directory: sep6/
        run: npm run serve
      - name: Cypress run
        uses: cypress-io/github-action@v2
 
