name: Cypress Tests

on: [push]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Setup npm package
        working-directory: sep6
        run: npm init -y && npm install && npm install -g @vue/cli@latest
      - name: Run Build
        run: npm run build
 
